

CREATE DATABASE YemekKutusu

USE YemekKutusu

CREATE TABLE Food
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,[Name]  NVARCHAR(100) NOT NULL
,ImagePath NVARCHAR(200)
,[Description] NVARCHAR(MAX)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
--,ImageFile VARBINARY(MAX)--Resmi DB de tutmak için.
)
CREATE TABLE Category
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,[Name]  NVARCHAR(100) NOT NULL
,MainId SMALLINT
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE FoodCategory
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,[Name]  NVARCHAR(100) NOT NULL
,FoodId SMALLINT REFERENCES Food(Id)
,CategoryId SMALLINT REFERENCES Category(Id)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE Restaurant
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,[Name]  NVARCHAR(100) NOT NULL
,[Adress] NVARCHAR (MAX)
,[MinOrderPay] MONEY
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE RestaurantAddress
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,RestaurantId SMALLINT REFERENCES Restaurant(Id)
,[Adress] NVARCHAR (MAX)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE RestaurantFood
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,RestaurantId SMALLINT REFERENCES Restaurant(Id)
,FoodId SMALLINT REFERENCES Food(Id)
,Price MONEY
,MaxQuantity TINYINT 
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE [User]
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,[Name] NVARCHAR(100) NOT NULL
,Surname NVARCHAR(100) NOT NULL
,Adress NVARCHAR(MAX) NOT NULL
,Age TINYINT
,Email NVARCHAR(100)
,Phone NVARCHAR(MAX)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE FoodCart
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,UserId SMALLINT REFERENCES [User](Id)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE FoodCartItem
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,FoodCartId SMALLINT REFERENCES FoodCart(Id)
,FoodId SMALLINT REFERENCES Food(Id)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)

CREATE TABLE UserAddress
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,UserId SMALLINT REFERENCES [User](Id)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE [Order]
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,UserId SMALLINT REFERENCES [User](Id)
,FoodId SMALLINT REFERENCES Food(Id)
,OrderPay MONEY
,OrderPiece TINYINT
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE OrderDetail
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,OrderId SMALLINT REFERENCES  [Order](Id)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE OrderAddress
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,OrderId SMALLINT REFERENCES  [Order](Id)
,UserAddressId SMALLINT REFERENCES  UserAddress(Id)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE Payment
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,OrderId SMALLINT REFERENCES  [Order](Id)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE OrderRateType
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE OrderRate
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,OrderId SMALLINT REFERENCES  [Order](Id)
,OrderRateTypeId SMALLINT REFERENCES OrderRate(Id)
,Point TINYINT
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE OrderComment
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,OrderId SMALLINT REFERENCES  [Order](Id)
,UserId SMALLINT REFERENCES [User](Id)
,Point TINYINT
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE OrderTip
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,OrderId SMALLINT REFERENCES  [Order](Id)
,UserId SMALLINT REFERENCES [User](Id)
,TipAmount MONEY
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE FavRestaurant
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,UserId SMALLINT REFERENCES [User](Id)
,RestaurantId SMALLINT REFERENCES Restaurant(Id)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE JokerDiscount
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE JokerRestaurant
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,RestaurantId SMALLINT REFERENCES Restaurant(Id)
,JokerDiscountId SMALLINT REFERENCES JokerDiscount(Id)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE UserPoint
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,UserId SMALLINT REFERENCES [User](Id)
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE Campaign
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE Setting
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
CREATE TABLE Slider
(
Id SMALLINT IDENTITY(1,1) PRIMARY KEY
,IsActive BIT
,IsDeleted BIT
,CreDate DATETIME
,CreUserId SMALLINT
)
--https://github.com/ErenZede
SELECT*FROM YemekKutusu






